import mariadb from "../database/mariadb.js";
var timerecords = [
  {
    datetime: "2021-05-03",
    "user.name": "Teste1",
    "user.idx_name": 1002,
    "user.user_id": "2",
    "user.idx_user_id": 1002,
    "user.idx_user_id_num": 1002,
    "user.user_group.id": 1,
    "user.user_group.name": "All Users",
    "shift.name": "H1",
    "shift.overtime_rule_shift": 0,
    leaves: "[]",
    leave_pay_code_ids: null,
    leave_pay_code_names: null,
    leave_count: 0,
    exceptions: "[2]",
    exception_codes: "TA_EXCEPTION_2",
    in_time: null,
    rounding_in: null,
    out_time: null,
    rounding_out: null,
    "normal.regular": 0,
    "normal.overtime": 0,
    "normal.worked_leave_time": 0,
    "normal.non_worked_leave_time": 0,
    "time_rate.regular": 0,
    "time_rate.overtime": 0,
    "time_rate.worked_leave_time": null,
    "time_rate.non_wkd_leave_time": null,
    "break.punch_break": 0,
    "break.over_break": 0,
    "meal_time.auto": 0,
    "meal_time.by_punch": 0,
    total_work_time: 0,
    total_rule_overtime: 0,
    total_time_rate_rule_overtime: 0,
    regular_pay_code_id: 1,
    session_id: "lRdY2rBw4oaWpvHJRALU0lpO",
  },
  {
    datetime: "2021-05-04",
    "user.name": "Teste1",
    "user.idx_name": 1002,
    "user.user_id": "2",
    "user.idx_user_id": 1002,
    "user.idx_user_id_num": 1002,
    "user.user_group.id": 1,
    "user.user_group.name": "All Users",
    "shift.name": "H1",
    "shift.overtime_rule_shift": 0,
    leaves: "[]",
    leave_pay_code_ids: null,
    leave_pay_code_names: null,
    leave_count: 0,
    exceptions: "[2]",
    exception_codes: "TA_EXCEPTION_2",
    in_time: null,
    rounding_in: null,
    out_time: null,
    rounding_out: null,
    "normal.regular": 0,
    "normal.overtime": 0,
    "normal.worked_leave_time": 0,
    "normal.non_worked_leave_time": 0,
    "time_rate.regular": 0,
    "time_rate.overtime": 0,
    "time_rate.worked_leave_time": null,
    "time_rate.non_wkd_leave_time": null,
    "break.punch_break": 0,
    "break.over_break": 0,
    "meal_time.auto": 0,
    "meal_time.by_punch": 0,
    total_work_time: 0,
    total_rule_overtime: 0,
    total_time_rate_rule_overtime: 0,
    regular_pay_code_id: 1,
    session_id: "lRdY2rBw4oaWpvHJRALU0lpO",
  },
  {
    datetime: "2021-05-05",
    "user.name": "Teste1",
    "user.idx_name": 1002,
    "user.user_id": "2",
    "user.idx_user_id": 1002,
    "user.idx_user_id_num": 1002,
    "user.user_group.id": 1,
    "user.user_group.name": "All Users",
    "shift.name": "H1",
    "shift.overtime_rule_shift": 0,
    leaves: "[]",
    leave_pay_code_ids: null,
    leave_pay_code_names: null,
    leave_count: 0,
    exceptions: "[2]",
    exception_codes: "TA_EXCEPTION_2",
    in_time: null,
    rounding_in: null,
    out_time: null,
    rounding_out: null,
    "normal.regular": 0,
    "normal.overtime": 0,
    "normal.worked_leave_time": 0,
    "normal.non_worked_leave_time": 0,
    "time_rate.regular": 0,
    "time_rate.overtime": 0,
    "time_rate.worked_leave_time": null,
    "time_rate.non_wkd_leave_time": null,
    "break.punch_break": 0,
    "break.over_break": 0,
    "meal_time.auto": 0,
    "meal_time.by_punch": 0,
    total_work_time: 0,
    total_rule_overtime: 0,
    total_time_rate_rule_overtime: 0,
    regular_pay_code_id: 1,
    session_id: "lRdY2rBw4oaWpvHJRALU0lpO",
  },
  {
    datetime: "2021-05-06",
    "user.name": "Teste1",
    "user.idx_name": 1002,
    "user.user_id": "2",
    "user.idx_user_id": 1002,
    "user.idx_user_id_num": 1002,
    "user.user_group.id": 1,
    "user.user_group.name": "All Users",
    "shift.name": "H1",
    "shift.overtime_rule_shift": 0,
    leaves: "[]",
    leave_pay_code_ids: null,
    leave_pay_code_names: null,
    leave_count: 0,
    exceptions: "[2]",
    exception_codes: "TA_EXCEPTION_2",
    in_time: null,
    rounding_in: null,
    out_time: null,
    rounding_out: null,
    "normal.regular": 0,
    "normal.overtime": 0,
    "normal.worked_leave_time": 0,
    "normal.non_worked_leave_time": 0,
    "time_rate.regular": 0,
    "time_rate.overtime": 0,
    "time_rate.worked_leave_time": null,
    "time_rate.non_wkd_leave_time": null,
    "break.punch_break": 0,
    "break.over_break": 0,
    "meal_time.auto": 0,
    "meal_time.by_punch": 0,
    total_work_time: 0,
    total_rule_overtime: 0,
    total_time_rate_rule_overtime: 0,
    regular_pay_code_id: 1,
    session_id: "lRdY2rBw4oaWpvHJRALU0lpO",
  },
  {
    datetime: "2021-05-07",
    "user.name": "Teste1",
    "user.idx_name": 1002,
    "user.user_id": "2",
    "user.idx_user_id": 1002,
    "user.idx_user_id_num": 1002,
    "user.user_group.id": 1,
    "user.user_group.name": "All Users",
    "shift.name": "H1",
    "shift.overtime_rule_shift": 0,
    leaves: "[]",
    leave_pay_code_ids: null,
    leave_pay_code_names: null,
    leave_count: 0,
    exceptions: "[2]",
    exception_codes: "TA_EXCEPTION_2",
    in_time: null,
    rounding_in: null,
    out_time: null,
    rounding_out: null,
    "normal.regular": 0,
    "normal.overtime": 0,
    "normal.worked_leave_time": 0,
    "normal.non_worked_leave_time": 0,
    "time_rate.regular": 0,
    "time_rate.overtime": 0,
    "time_rate.worked_leave_time": null,
    "time_rate.non_wkd_leave_time": null,
    "break.punch_break": 0,
    "break.over_break": 0,
    "meal_time.auto": 0,
    "meal_time.by_punch": 0,
    total_work_time: 0,
    total_rule_overtime: 0,
    total_time_rate_rule_overtime: 0,
    regular_pay_code_id: 1,
    session_id: "lRdY2rBw4oaWpvHJRALU0lpO",
  },
  {
    datetime: "2021-05-10",
    "user.name": "Teste1",
    "user.idx_name": 1002,
    "user.user_id": "2",
    "user.idx_user_id": 1002,
    "user.idx_user_id_num": 1002,
    "user.user_group.id": 1,
    "user.user_group.name": "All Users",
    "shift.name": "H1",
    "shift.overtime_rule_shift": 0,
    leaves: "[]",
    leave_pay_code_ids: null,
    leave_pay_code_names: null,
    leave_count: 0,
    exceptions: "[2]",
    exception_codes: "TA_EXCEPTION_2",
    in_time: null,
    rounding_in: null,
    out_time: null,
    rounding_out: null,
    "normal.regular": 0,
    "normal.overtime": 0,
    "normal.worked_leave_time": 0,
    "normal.non_worked_leave_time": 0,
    "time_rate.regular": 0,
    "time_rate.overtime": 0,
    "time_rate.worked_leave_time": null,
    "time_rate.non_wkd_leave_time": null,
    "break.punch_break": 0,
    "break.over_break": 0,
    "meal_time.auto": 0,
    "meal_time.by_punch": 0,
    total_work_time: 0,
    total_rule_overtime: 0,
    total_time_rate_rule_overtime: 0,
    regular_pay_code_id: 1,
    session_id: "lRdY2rBw4oaWpvHJRALU0lpO",
  },
  {
    datetime: "2021-04-28",
    "user.name": "Teste1",
    "user.idx_name": 1002,
    "user.user_id": "2",
    "user.idx_user_id": 1002,
    "user.idx_user_id_num": 1002,
    "user.user_group.id": 1,
    "user.user_group.name": "All Users",
    "shift.name": "H1",
    "shift.overtime_rule_shift": 0,
    leaves: "[]",
    leave_pay_code_ids: null,
    leave_pay_code_names: null,
    leave_count: 0,
    exceptions: "[12,3,4]",
    exception_codes: "TA_EXCEPTION_12,TA_EXCEPTION_3,TA_EXCEPTION_4",
    in_time: "2021-04-28T17:39:13.000Z",
    rounding_in: null,
    out_time: "2021-04-28T17:39:22.000Z",
    rounding_out: null,
    "normal.regular": 9,
    "normal.overtime": 0,
    "normal.worked_leave_time": 0,
    "normal.non_worked_leave_time": 0,
    "time_rate.regular": 9,
    "time_rate.overtime": 0,
    "time_rate.worked_leave_time": null,
    "time_rate.non_wkd_leave_time": null,
    "break.punch_break": 0,
    "break.over_break": 0,
    "meal_time.auto": 0,
    "meal_time.by_punch": 0,
    total_work_time: 9,
    total_rule_overtime: 0,
    total_time_rate_rule_overtime: 0,
    regular_pay_code_id: 1,
    session_id: "lRdY2rBw4oaWpvHJRALU0lpO",
  },
  {
    datetime: "2021-04-29",
    "user.name": "Teste1",
    "user.idx_name": 1002,
    "user.user_id": "2",
    "user.idx_user_id": 1002,
    "user.idx_user_id_num": 1002,
    "user.user_group.id": 1,
    "user.user_group.name": "All Users",
    "shift.name": "H1",
    "shift.overtime_rule_shift": 0,
    leaves: "[]",
    leave_pay_code_ids: null,
    leave_pay_code_names: null,
    leave_count: 0,
    exceptions: "[2]",
    exception_codes: "TA_EXCEPTION_2",
    in_time: null,
    rounding_in: null,
    out_time: null,
    rounding_out: null,
    "normal.regular": 0,
    "normal.overtime": 0,
    "normal.worked_leave_time": 0,
    "normal.non_worked_leave_time": 0,
    "time_rate.regular": 0,
    "time_rate.overtime": 0,
    "time_rate.worked_leave_time": null,
    "time_rate.non_wkd_leave_time": null,
    "break.punch_break": 0,
    "break.over_break": 0,
    "meal_time.auto": 0,
    "meal_time.by_punch": 0,
    total_work_time: 0,
    total_rule_overtime: 0,
    total_time_rate_rule_overtime: 0,
    regular_pay_code_id: 1,
    session_id: "lRdY2rBw4oaWpvHJRALU0lpO",
  },
  {
    datetime: "2021-04-30",
    "user.name": "Teste1",
    "user.idx_name": 1002,
    "user.user_id": "2",
    "user.idx_user_id": 1002,
    "user.idx_user_id_num": 1002,
    "user.user_group.id": 1,
    "user.user_group.name": "All Users",
    "shift.name": "H1",
    "shift.overtime_rule_shift": 0,
    leaves: "[]",
    leave_pay_code_ids: null,
    leave_pay_code_names: null,
    leave_count: 0,
    exceptions: "[2]",
    exception_codes: "TA_EXCEPTION_2",
    in_time: null,
    rounding_in: null,
    out_time: null,
    rounding_out: null,
    "normal.regular": 0,
    "normal.overtime": 0,
    "normal.worked_leave_time": 0,
    "normal.non_worked_leave_time": 0,
    "time_rate.regular": 0,
    "time_rate.overtime": 0,
    "time_rate.worked_leave_time": null,
    "time_rate.non_wkd_leave_time": null,
    "break.punch_break": 0,
    "break.over_break": 0,
    "meal_time.auto": 0,
    "meal_time.by_punch": 0,
    total_work_time: 0,
    total_rule_overtime: 0,
    total_time_rate_rule_overtime: 0,
    regular_pay_code_id: 1,
    session_id: "lRdY2rBw4oaWpvHJRALU0lpO",
  },
];

var getTimeCardReportDetail = async () => {
  let conn;
  try {
    // let rows = timerecords;

    // rows = rows.map((row) => {
    //   return {
    //     Date: row.datetime,
    //     UserName: row["user.idx_name"],
    //   };
    // });

    // console.log(rows);

    // return rows;

    conn = await mariadb.getConnection();
    let rows = await conn.query(`select * from View_TimeCard;`);

    
    return rows;

    // rows = rows.map((row) => {
    //   return {
    //     Date: row.date,
    //     Name: row.name,
    //     UserId: row.user_id,
    //     Department: "",
    //     Shift: row.shift_name,
    //     firstTime: {
    //       clockInDefault: "7:00:00",
    //       clockIn: "7:00:00",
    //       clockOut: "14:00:00",
    //       timeLate: "00:00:00",
    //       extraHours: "00:00:00",
    //       regularHours: "6:00:00",
    //       totalTime: "5:40:00",
    //     },
    //     ...row,
    //   };
    // });

    return rows;
  } catch (err) {
    throw err;
  } finally {
    if (conn) conn.release(); //release to pool
  }
};

export default {
  getTimeCardReportDetail,
};
